globalVariables(
  c(
    ".",
    "author",
    "gutenberg_author_id",
    "gutenberg_id",
    "gutenberg_languages",
    "gutenberg_metadata",
    "has_text",
    "is_header",
    "language",
    "n",
    "number",
    "section",
    "text",
    "title",
    "total",
    "total_languages"
  )
)
